"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const _ = require("lodash");
const crypto = require("crypto");
function mb5(data) {
    return crypto.createHash('md5').update(data).digest('hex');
}
// TODO add dependency
class BaseCache {
    constructor() {
        /**
         * @type {string} a string prefixed to every cache key so that it is unique globally in the whole cache storage.
         * It is recommended that you set a unique cache key prefix for each application if the same cache
         * storage is being used by different applications.
         *
         * To ensure interoperability, only alphanumeric characters should be used.
         */
        this.keyPrefix = '';
        this.serialization = true;
    }
    /**
     * Builds a normalized cache key from a given key.
     *
     * If the given key is a string containing alphanumeric characters only and no more than 32 characters,
     * then the key will be returned back prefixed with [[keyPrefix]]. Otherwise, a normalized key
     * is generated by serializing the given key, applying MD5 hashing, and prefixing with [[keyPrefix]].
     *
     * @param key the key to be normalized
     * @returns {string} the generated cache key
     */
    buildKey(key) {
        if (_.isString(key)) {
            key = key.length <= 32 ? key : mb5(key);
        }
        else {
            key = mb5(JSON.stringify(key));
        }
        return this.keyPrefix + key;
    }
    /**
     * Retrieves a value from cache with a specified key.
     *
     * @param key a key identifying the cached value. This can be a simple string or
     * a complex data structure consisting of factors representing the key.
     * @returns {any} the value stored in cache, false if the value is not in the cache, expired.
     */
    get(key) {
        key = this.buildKey(key);
        let value = this.getValue(key);
        if (value === false || this.serialization === false) {
            return value;
        }
        return JSON.parse(value);
    }
    /**
     * Retrieves multiple values from cache with the specified keys.
     * @param {any[]} keys list of string keys identifying the cached values
     * @return {any} list of cached values corresponding to the specified keys. The list
     * is returned in terms of (key, value) pairs.
     * If a value is not cached or expired, the corresponding array value will be false.
     */
    multiGet(keys) {
        const keyMap = {};
        for (const key of keys) {
            keyMap[key] = this.buildKey(key);
        }
        const values = this.getValues(_.values(keyMap));
        const results = {};
        _.forEach(keyMap, (newKey, key) => {
            results[key] = false;
            if (values[newKey] !== undefined) {
                if (!this.serialization) {
                    results[key] = values[newKey];
                }
                else {
                    results[key] = JSON.parse(values[newKey]);
                }
            }
        });
        return results;
    }
    /**
     * Checks whether a specified key exists in the cache.
     * This can be faster than getting the value from the cache if the data is big.
     * In case a cache does not support this feature natively, this method will try to simulate it
     * but has no performance improvement over getting it.
     *
     * @param key a key identifying the cached value. This can be a simple string or
     * a complex data structure consisting of factors representing the key.
     * @returns {boolean} true if a value exists in cache, false if the value is not in the cache or expired.
     */
    exists(key) {
        key = this.buildKey(key);
        const value = this.getValue(key);
        return value !== false;
    }
    /**
     * Stores a value identified by a key into cache.
     * If the cache already contains such a key, the existing value and
     * expiration time will be replaced with the new ones, respectively.
     *
     * @param key a key identifying the value to be cached. This can be a simple string or
     * a complex data structure consisting of factors representing the key.
     * @param value the value to be cached
     * @param {number} duration the number of seconds in which the cached value will expire. 0 means never expire.
     * @returns {boolean} whether the value is successfully stored into cache
     */
    set(key, value, duration = 0) {
        key = this.buildKey(key);
        if (this.serialization === true) {
            value = JSON.stringify(value);
        }
        return this.setValue(key, value, duration);
    }
    /**
     * Stores multiple items in cache. Each item contains a value identified by a key.
     * If the cache already contains such a key, the existing value and
     * expiration time will be replaced with the new ones, respectively.
     *
     * @param {any} items the items to be cached, as key-value pairs.
     * @param int {number} duration the number of seconds in which the cached values will expire. 0 means never expire.
     * @return {any[]} array of failed keys
     */
    multiSet(items, duration = 0) {
        const data = {};
        _.forEach(items, (value, key) => {
            if (this.serialization === true) {
                value = JSON.stringify(value);
            }
            key = this.buildKey(key);
            data[key] = value;
        });
        return this.setValues(data, duration);
    }
    /**
     * Stores a value identified by a key into cache if the cache does not contain this key.
     * Nothing will be done if the cache already contains the key.
     *
     * @param key a key identifying the value to be cached. This can be a simple string or
     * a complex data structure consisting of factors representing the key.
     * @param value the value to be cached
     * @param {number} duration the number of seconds in which the cached value will expire. 0 means never expire.
     * @returns {boolean} whether the value is successfully stored into cache
     */
    add(key, value, duration = 0) {
        key = this.buildKey(key);
        if (this.serialization === true) {
            value = JSON.stringify(value);
        }
        return this.addValue(key, value, duration);
    }
    /**
     * Stores multiple items in cache. Each item contains a value identified by a key.
     * If the cache already contains such a key, the existing value and expiration time will be preserved.
     *
     * @param {any} items the items to be cached, as key-value pairs.
     * @param {number} duration the number of seconds in which the cached values will expire. 0 means never expire.
     * @return {any[]} array of failed keys
     */
    multiAdd(items, duration = 0) {
        const data = {};
        _.forEach(items, (value, key) => {
            if (this.serialization === true) {
                value = JSON.stringify(value);
            }
            key = this.buildKey(key);
            data[key] = value;
        });
        return this.addValues(data, duration);
    }
    /**
     * Deletes a value with the specified key from cache
     *
     * @param key a key identifying the value to be deleted from cache. This can be a simple string or
     * a complex data structure consisting of factors representing the key.
     * @returns {boolean} if no error happens during deletion
     */
    delete(key) {
        key = this.buildKey(key);
        return this.deleteValue(key);
    }
    /**
     * Deletes all values from cache.
     * Be careful of performing this operation if the cache is shared among multiple applications.
     *
     * @returns {boolean} whether the flush operation was successful.
     */
    flush() {
        return this.flushValues();
    }
    /**
     * Retrieves multiple values from cache with the specified keys.
     * The default implementation calls [[getValue()]] multiple times to retrieve
     * the cached values one by one. If the underlying cache storage supports multiget,
     * this method should be overridden to exploit that feature.
     *
     * @param {string[]} keys a list of keys identifying the cached values
     * @returns {any} a list of cached values indexed by the keys
     */
    getValues(keys) {
        const results = {};
        for (const key of keys) {
            results[key] = this.getValue(key);
        }
        return results;
    }
    /**
     * Stores multiple key-value pairs in cache.
     * The default implementation calls [[setValue()]] multiple times store values one by one. If the underlying cache
     * storage supports multi-set, this method should be overridden to exploit that feature.
     *
     * @param data array where key corresponds to cache key while value is the value stored
     * @param duration the number of seconds in which the cached values will expire. 0 means never expire.
     * @returns {any[]} array of failed keys
     */
    setValues(data, duration) {
        const failedKeys = [];
        _.forEach(data, (value, key) => {
            if (this.setValue(key, value, duration) === false) {
                failedKeys.push(key);
            }
        });
        return failedKeys;
    }
    /**
     * Stores multiple key-value pairs in cache.
     * The default implementation calls [[setValue()]] multiple times store values one by one. If the underlying cache
     * storage supports multi-set, this method should be overridden to exploit that feature.
     *
     * @param {any} data array where key corresponds to cache key while value is the value stored
     * @param {number} duration the number of seconds in which the cached values will expire. 0 means never expire.
     * @returns {any[]} array of failed keys
     */
    addValues(data, duration) {
        const failedKeys = [];
        _.forEach(data, (value, key) => {
            if (this.addValue(key, value, duration) === false) {
                failedKeys.push(key);
            }
        });
        return failedKeys;
    }
}
exports.BaseCache = BaseCache;
